name: acmesoftware

services:
  police-server:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/acmesoftware/police-server:latest
    container_name: police-server
    ports:
      - 1234:8000
    restart: unless-stopped
